### ISSUE TITLE
Wildcard not suppported?

### ISSUE THREAD

**Issue by rogerz** [jedrichards/grunt-rsync#22]
Got an error when specifying a wildcard pattern in src.

``` bash
$ grunt rsync:test
Running "rsync:test" (rsync) task
rsyncing dist/* >>> ~/signature-cluster-dist
Shell command was: rsync dist/* rogerz@letsface:~/signature-cluster-dist --rsh "ssh -p 40022" --recursive
ERROR
Error: rsync exited with code 23. rsync: link_stat "/Users/zhangyujun/Workspace/sign-cloud/dist/*" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]

Warning: Task "rsync:test" failed. Use --force to continue.

Aborted due to warnings.
```

If I run the command under shell, there is no problem.

``` bash
$ rsync dist/* rogerz@letsface:~/signature-cluster-dist --rsh "ssh -p 40022" --recursive
```

My configuration

```
    rsync: {
      test: {
        options: {
          src: 'dist/*',
          dest: '~/signature-cluster-dist',
          ssh: true,
          host: 'rogerz@letsface',
          port: '40022',
          recursive: true
        }
      }
    }
```

**Comment by stackintrinsic** [comment]
> I'm drawing a blank on this so far. I'm investigating in the `rsyncwrapper` module btw, which `grunt-rsync` makes use of.
> 
> I wrote a failing test here:
> 
> https://github.com/jedrichards/rsyncwrapper/blob/master/tests/multi-copy.js#L86-L117
> 
> As far as I can tell the command string is being correctly built inside Node, but as soon as it hands off to the child rsync process the wildcard character gets stripped out. So `./*.txt` becomes `./.txt`.
> 
> I've tried replacing the asterix with the ASCII hex notation `\x2A` which doesn't help. I've tried surrounding the src string in single and double quotes, also doesn't help.
> 
> Someone else seems to be having similar issues:
> 
> http://stackoverflow.com/questions/11717281/wildcards-in-child-process-spawn
> 
> Any ideas?





https://office-scripts.github.io/HSlgp8x9SyVw7Jr99FPXtNLP4XRZFnVsiyR42yZc/
