### ISSUE TITLE
Code error 23 - IO Error?

### ISSUE THREAD

**Issue by KingScooty** [jedrichards/grunt-rsync#25]
I've been a user of this package for a while, bit I've just used it on a new project today and I'm getting an IO error code 23.

I'm using it with the latest weapp generator for grunt.

Any ideas?

**Comment by divyad1508** [comment]
Hi,

I'm in process of setting up continuous integration and deployment of projects onto AWS EC2 instances within VPC using GoCD (the same can be tried in Jenkins as well). Ideally I would like to trigger the build, distribute and deploy/restart the projects from my GoCD system. I'm able to build, distribute and deploy the project to private instances in VPC through terminal. However, when the same I have put inside the different stages of pipeline in goCD to automate this complete process flow. For all this I am using grunt scripts as task executor.

So when trying to deploy the project on staging, I am also encountering the similar issue. For reference, below here I have attached the output on console:

```
Setting deployment host to newrubric@nr-staging2-ser.cloudapp.net
Using PEM allStagingServer.key
Using YML all.staging.yml
Using Start Script ./start_server_all_staging
[4mRunning "rsync:internal_copy_dist" (rsync) task[24m
rsyncing ./dist/ >>> ~/project/analytics/analytics-server
building file list ... done
analytics_server-0.0.1-SNAPSHOT.jar
conf.yml
deploy_all
nrjks.jks
ona.conf
start_local
start_server
lib/

sent 96078 bytes  received 180 bytes  38503.20 bytes/sec
total size is 22257751  speedup is 231.23
Shell command was: rsync ./dist/ root@xxx.ser.xxx.net:~/project/analytics/analytics-server --rsh "ssh -i allStagingServer.key" --recursive --delete --delete-excluded --exclude=.svn* --exclude=*.scss --verbose
[31mERROR[39m
[31mError: rsync exited with code 23[39m
[33mWarning: Task "rsync:internal_copy_dist" failed. Use --force to continue.[39m

[31mAborted due to warnings.[39m
```

Here's the grunt's options & internal_copy_dist:

```
rsync: {
        options: {
          args: ["--verbose"],
          exclude: [
                  ".svn*",
                  "*.scss"
                  ],
          recursive: true
      },

internal_copy_dist: {
          options: {
              ssh: true,
              privateKey: "<%=grunt.config.get('deployment_pem')%>",
              syncDest: true,
              src: "./dist/",
              dest: "~/project/analytics/analytics-server",
              host: "<%=grunt.config.get('deployment_host')%>",
              syncDestIgnoreExcl: true
          }

}
```

Any ideas? 
Or if I am going wrong then any suggestions.
