### ISSUE TITLE
problem with destination directory

### ISSUE THREAD

**Issue by miguelsneto** [jedrichards/grunt-rsync#40]
When I deploy to production the grunt-rsync creates a new directory to place the files. but I need it to just put the files without creating the directory on the target directory.
How I can do this?

**Comment by jedrichards** [comment]
Try putting a `/` at the end of the dest path. So src and dest options a bit like,

```
src: "dist/",
dest: "/var/www/site/",
```

should copy the contents of `dist` into the `site` folder, assuming the `site` folder already exists ...

**Comment by miguelsneto** [comment]
It really was that.
Sorry for the inconvenience. Silly question.
Source directory was set to a variable without "/"
