### ISSUE TITLE
Copying in subfolder on host

### ISSUE THREAD

**Issue by iDuuck** [jedrichards/grunt-rsync#41]
Hello,
when I am trying to upload the file to a host `grunt-rsync` is uploading the files in the subfolder that looks like the `src` option. But I want the files to be in the specified `dest` option folder. How to achieve this?
my grunt config looks like this:
```
rsync: {
  options: {
    args: ['--verbose'],
    exclude: ['.git*','*.scss','.DS_Store','node_modules'],
    recursive: true,   
    delete: true
  },
  production: {
    options: {
      src: './dist',
      dest: '/path/to/deployment',
      host: 'root@domain.tld',
    }
  }
}
```

So, the file will all be uploaded to `/path/to/deployment/dist`. That's not what I want.

**Comment by jedrichards** [comment]
Does this issue help you? https://github.com/jedrichards/grunt-rsync/issues/40

**Comment by iDuuck** [comment]
Helped. Thanks!
