### ISSUE TITLE
Subfolder not syncing

### ISSUE THREAD

**Issue by iDuuck** [jedrichards/grunt-rsync#42]
I have another problem: I have a sub-sub-subfolder (`dist/app/images/projects/*****`). When I start `grunt rsync` everything is synced, but those folders aren't.

**Comment by jedrichards** [comment]
With the recursive option set to `true` the whole contents of the folder should be transferred ...

**Comment by iDuuck** [comment]
it IS set to `true`...

**Comment by iDuuck** [comment]
Just figured out that the `dist` folder had not included this. So it was because of my build task.
Thanks, though!

**Comment by jedrichards** [comment]
:+1:
