### ISSUE TITLE
Shell command was toggle

### ISSUE THREAD

**Issue by methnen** [jedrichards/grunt-rsync#44]
First great grunt task it came in super helpful to me recently, thank you.

Would be great if there were an option to disable the `Shell command was: rsync...` output after the command runs.

**Comment by jedrichards** [comment]
Thanks! Is it just the `Shell command was:` message that's troubling you, or all the output?

**Comment by methnen** [comment]
Yeah, just that part. It's not troubling really, just using it in a situation where it would be nice to eliminate that part of the output, since grunt-rsync is being run in tandem with a bunch of other tasks. that also have output and I'm trying to pair it all down to just the necessary bits for whoever's run the task.

**Comment by jedrichards** [comment]
Maybe we could use the grunt.verbose to log some of the stuff,

http://gruntjs.com/api/grunt.log#verbose-and-notverbose

then you could still still that info with `grunt taskname --verbose` but by default it wouldn't show. Would that work?

I'm happy to do this, but might not get around to it for a while. Feel free to make a PR though, I'll merge it right away.

**Comment by methnen** [comment]
I'm pretty swamped but if I have some time and you haven't gotten to it yet I'll look into it. :) Thanks again.

**Comment by jedrichards** [comment]
Gonna close for now since it doesn't seem to have much traction. Feel free to re-open if/when :)
