### ISSUE TITLE
process hangs

### ISSUE THREAD

**Issue by illiptic** [jedrichards/grunt-rsync#47]
I have a grunt task that runs multiple rsync tasks configured like so:

    rsync: {
            options: {
                args: ['--verbose -a'],
                recursive: true,
                delete: true
            },
            fonts: {
                options: {
                    src: '<%= srcPath %>/site/fonts/',
                    dest: '<%= wrkPath %>/fonts',
                    exclude: [
                        'libs/'
                    ]
                }
            },
            etc.....

All of them just hang, no output whatsoever.
If I try using rsync directly, it works normally.

Also, if I check the filesystem, the destination folders are created.

I'm running grunt (and rsync) from cygwin. 

Any ideas?

Versions:
rsync  version 3.1.1  protocol version 31
grunt-cli v0.1.13
grunt v0.4.5
grunt-rsync v0.6.2

**Comment by jedrichards** [comment]
Have you tried reducing your config down to something minimal? i.e. a single task doing something very simply and see if it works?

From the issues here I know some people are using this on Cygwin with success but I don't have a Windows machine so haven't been able to test it properly.

**Comment by illiptic** [comment]
I'll try that and come back to you. Thanks!

**Comment by illiptic** [comment]
Good news for you, bad for me:

The grunt task started hanging again, without any errors preceding it.
Also, the gulp-rsync task I used last time to "unlock" it hangs the same way.

So my issue has obviously nothing to do with grunt-rsync!

**Comment by jedrichards** [comment]
Ah! Ok, good luck with your issue.
