### ISSUE TITLE
rsync on windows server

### ISSUE THREAD

**Issue by wanghaisheng** [jedrichards/grunt-rsync#48]
>A reasonably modern version of rsync (>=v2.6.9) in your PATH.
 does this mean i should install cwrsync or something like this to use your grunt-rsync

**Comment by jedrichards** [comment]
Hi! Yep as far as I know there are Windows users happily using cwrsync and this task. There is code in the task specifically for Windows compatibility.

If you search the issues in this repo for "windows" or "cwrsync" you might find some info to help you, i.e. problems Windows users had and how to fix.

**Comment by wanghaisheng** [comment]
cwrsync  is not free or at least server is not
is this project act as a client or can it be both client and server

**Comment by jedrichards** [comment]
Just client. You can move files around locally, or move files from the local system to a remote system over ssh. It's not anything to do with a rsync server/daemon.

**Comment by wanghaisheng** [comment]
if  i have two windows server machine, the only thing what i got to do is deploy this project to server machine ,and client machine can receive the specified file changes in one folder?

**Comment by jedrichards** [comment]
So something like this?

```
[Windows Server 1]  --- deploy files using ssh --->  [Windows Server 2]
```

Yes ... should work. Anything you can do with the `rsync` command normally, you should be able to do with this task.

**Comment by wanghaisheng** [comment]
can i use [this](http://sourceforge.net/projects/rsyncforwindows/)  as your rsync  pre-requirement ?
i still did not get what dou you mean by " rsync (>=v2.6.9) in your PATH." 
which one i should download and install?do i need to configure system environment variable in path?

**Comment by jedrichards** [comment]
I'm not a Windows developer so I'm not sure about that link, all I know is that some users have reported using cwrsync with success.

> i still did not get what dou you mean by " rsync (>=v2.6.9) in your PATH." which one i should download and install?do i need to configure system environment variable in path?

As long as you can call `rsync` from your prompt, then this task should run properly.

**Comment by wanghaisheng** [comment]
as i said cwrsync is not free or at least server is not 
but i get what you mean 
thxs
