### ISSUE TITLE
windows server problem

### ISSUE THREAD

**Issue by WinLinKer** [jedrichards/grunt-rsync#53]
hello,on my windows server 2016,i can connect via authorized_keys,but i didn't know how to write  the dest format,i tried   "/C:/Users/xxx", "\/C\:\/Users\/xxx",but all failed.so can u help me to solve this problem?

**Comment by jedrichards** [comment]
Hmm, I'm not sure - I haven't used Windows for a long time. I know user's of this lib are using Windows happily though.

Should your desk paths have the `/` at the beginning?

**Comment by WinLinKer** [comment]
thanks for your reply,maybe have the other way to resolve,i will try.
