### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by alpha-and-omega** [jedrichards/grunt-rsync#54]
I would like to contribute this knowledge:
If you add --delay-updates and --delete-delay to rsync options, rsync will deploy code almost atomically.
This is **a must** on large codebase projects. This can be added to examples.

**Comment by jedrichards** [comment]
Sounds good. What are some of the benefits of atomic deployments in large code bases?

**Comment by alpha-and-omega** [comment]
Rsyncing of a large codebase is not instant, and during this time website visitors will see 500, 404 .. and other website errors due to mix of old/new files. These options eliminate this problem.
